# Site settings
title: Newman
# email: newman@usps.gov
description: > # this means to ignore newlines until "baseurl:"
    "When you control the mail, you control... information"
baseurl: "/testPages" # the subpath of your site, e.g. /blog/
url: "http://bwhiteman.github.io" # the base hostname & protocol for your site
# twitter_username: newmanusps
github_username:  Sotera
highlighter: pygments
github:
    user:Sotera
    repo:newman
downloadUrl: https://github.com/Sotera/newman/archive/master.zip

# Build settings
markdown: kramdown
