# Site settings
title: Newman
safe: true
lsi: false
# email: newman@usps.gov
description: > # this means to ignore newlines until "baseurl:"
    "When you control the mail, you control... information"
baseurl: "/testPages" # the subpath of your site, e.g. /blog/
url: "http://bwhiteman.github.io" # the base hostname & protocol for your site
# twitter_username: newmanusps
github_username:  Sotera
highlighter: pygments
show_downloads: true
zip_url: https://github.com/Sotera/newman/zipball/master
tar_url: https://github.com/Sotera/newman/tarball/master

# Build settings
# markdown: redcarpet
# redcarpet:
#   extensions: [no_fenced_code_blocks,]
